- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

# - name: remve the defalut conten in nginx from html dir
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/*
#     state: absent

# - name: download frontend code
#   ansible.builtin.get_url:
#     url: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip"
#     dest: /tmp/frontend.zip

# - name: extract frontend code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: import roles from common
  ansible.builtin.import_role:
      name: common
      tasks_from: main
      
- name: copy the expense.conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx
    

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted

